clockwork :
  url : https://api.clockwork.report
  token : wyWc+uUWY1WEYvR1kB4euMFhgj3Wx/B2Z+EbmBRssUUZAA16ilRHFPmkGqmuPSO7EpL2vgMpGn+ZwoygESa0N+pDVYqXM0R81KZwnA==--ou859rfEsaL4IFzD--6lCnR+zBJLhdk7Ys+n4Z+g==
oodo :
  project : SO/202207/422-CRDB API ESB
users :
    - name: Nuwan Walisundara
      tasks:
        - Design  
        - Internal discussions
        - CRDB design review
        - WSO2 Design review
      defaultTask: Design
    - name: Nuwan Senanayaka
